=== KayaTyan/OstranautsRuKaya/complete/data/data/schemas/conditions-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "strName": {
                "type": "string"
            },
            "strNameFriendly": {
                "type": "string"
            },
            "strColor": {
                "type": "string"
            },
            "strDesc": {
                "type": "string"
            },
            "bResetTimer": {
                "type": "boolean"
            },
            "nDisplaySelf": {
                "type": "integer"
            },
            "nDisplayOther": {
                "type": "integer"
            },
            "bFatal": {
                "type": "boolean"
            },
            "bRemoveAll": {
                "type": "boolean"
            },
            "aNext": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "fDuration": {
                "type": "number"
            },
            "bRemoveOnLoad": {
                "type": "boolean"
            },
            "aPer": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "fClampMax": {
                "type": "number"
            },
            "bKO": {
                "type": "boolean"
            },
            "bAlert": {
                "type": "boolean"
            },
            "strAnti": {
                "type": "string"
            },
            "bPersists": {
                "type": "boolean"
            },
            "pairFaceSprite": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "nValue": {
                        "type": "integer"
                    },
                    "strName": {
                        "type": "string"
                    }
                },
                "required": [
                    "nValue",
                    "strName"
                ]
            },
            "bRoom": {
                "type": "boolean"
            },
            "strCTImmune": {
                "type": "string"
            }
        },
        "required": [
            "strColor",
            "strDesc",
            "strName",
            "strNameFriendly"
        ]
    }
}

=== KayaTyan/OstranautsRuKaya/complete/data/data/conditions/conditions_stakes.json
[
  {
    "strName": "IsSTKTemplate_Fail_Cooldown",
    "strNameFriendly": "STKTemplate Перезарядка после сбоя",
    "strColor": "Neutral",
    "strDesc": "[us] попытался выполнить STKTemplate и пока не может повторить попытку.",
    "bResetTimer": true,
    "nDisplaySelf": 0,
    "nDisplayOther": 0,
    "fDuration": 0.1
  },
  {
    "strName": "IsSTKTemplate_Fail_Avoid",
    "strNameFriendly": "STKTemplate Мягкий сбой",
    "strColor": "Neutral",
    "strDesc": "[us] использовал мягкий сбой в STKTemplate, чтобы избежать жесткого сбоя, и пока не может использовать его снова.",
    "bResetTimer": true,
    "nDisplaySelf": 0,
    "nDisplayOther": 0,
    "fDuration": 0.1
  },
  {
    "strName": "IsSTKTemplate_Chitchat_Trait_Used",
    "strNameFriendly": "STKTemplate Особенность светской беседы использована",
    "strColor": "Neutral",
    "strDesc": "[us] использовал особенность светской беседы в STKTemplate и пока не может использовать ее снова.",
    "bResetTimer": true,
    "nDisplaySelf": 0,
    "nDisplayOther": 0,
    "fDuration": 0.1
  }
]

=== KayaTyan/OstranautsRuKaya/complete/data/conditions/conditions_plots_3act.json
[
  {
    "strName": "PlotTEMP3ActBEGStarted",
    "strNameFriendly": "PlotTEMP3ActBEGStarted",
    "strColor": "Neutral",
    "strDesc": "Запущен сюжет: TEMP3ActBEG.",
    "bResetTimer": false,
    "nDisplaySelf": 0,
    "nDisplayOther": 0,
    "bFatal": false,
    "bRemoveAll": false,
    "aNext": [],
    "fDuration": 0.0
  },
  {
    "strName": "PlotTEMP3ActBEGTaken",
    "strNameFriendly": "PlotTEMP3ActBEGTaken",
    "strColor": "Neutral",
    "strDesc": "Цель подверглась TEMP3ActBEG.",
    "bResetTimer": false,
    "nDisplaySelf": 0,
    "nDisplayOther": 0,
    "bFatal": false,
    "bRemoveAll": false,
    "aNext": [],
    "fDuration": 0.0
  }
]
