=== KayaTyan/OstranautsRuKaya/complete/data/data/schemas/plot-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "strName" : {
                "type": "string",
                "description": "The code name of the settings, as referred to."
            },
            "fTensionPeriod" : {
                "type": "number",
                "description": "Time in seconds between different tension events being spawned (bad)",
                "minimum": 0.0
            },
            "fReleasePeriod" : {
                "type": "number",
                "description": "Time in seconds between different release events being spawned (good).",
                "minimum": 0.0
            },
            "fAutosavePeriod" : {
                "type": "number",
                "description": "Time in seconds between autosaves.",
                "minimum": 0.0
            },
            "fSocialPeriod" : {
                "type": "number",
                "description": "Time in seconds after socialising before characters will socialise with the player again.",
                "minimum": 0.0
            },
            "dictEventChances": {
                "type": "object",
                "description": "Chances for specific plot events to occur\nAllchances must add up to 1.0",
                "properties": {
                    "bonus_derelict" : {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "description": "Chance the game spawns a better quality(less damaged) derelict the next time the player docks to a new derelict."
                    },
                    "mariner" : {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "description": "Chance the game spawns a mariner near the player"
                    },
                    "micrometeoroid" : {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "description": "Chance the game hits the player with a micrometeoroid"
                    },
                    "police_patrol" : {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "description": "Chance the police are spawned and lock onto the player"
                    },
                    "part_failure" : {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "description": "Chance one of the damaged parts spontaneously fails"
                    },
                    "emotional_clobber" : {
                        "type": "number",
                        "minimum": 0.0,
                        "maximum": 1.0,
                        "description": "Chance the player is clobbered by their own emotions"
                    }
                }
            }
        }
    }
}

=== KayaTyan/OstranautsRuKaya/complete/data/data/plot_manager/pm_settings.json
[
    {
		"strName" : "Plot Manager Settings",
		"fTensionPeriod" : 540,
		"fReleasePeriod" : 650,
		"fSocialPeriod" : 300,
		"fAutosavePeriod" : 903,
        "dictEventChances" : {
			"release_bonus_derelict" : 0.1,
			"release_meat_derelict" : 0.1,
			"release_plot" : 0.55,
			"release_reactor_part" : 0.05,
			"release_videotape" : 0.2,
			"tension_meat_derelict" : 0.05,
			"tension_plot" : 0.5,
			"tension_mariner" : 0.05,
			"tension_micrometeoroid" : 0.025,
			"tension_police_patrol" : 0.05,
			"tension_part_failure" : 0.125,
			"tension_emotional_clobber" : 0.05,
			"tension_message_from_derelict" : 0.025,
			"tension_pirate_spawn" : 0.075,
			"tension_factionship" : 0.05
		}
	}
]
